backend:
  name: github
  repo: hyo07/hugo-test
  branch: master

publish_mode: editorial_workflow

media_folder: "static/img/banners"
public_folder: "/img/banners"

collections:
  - name: "post"
    label: "Post"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Descreption", name: "description", widget: "text"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Category", name: "categories", widget: "list", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
